=== Smile-Liu/spex/spex-beans/src/org/spex/beans/factory/xml/spex-beans.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns="http://www.spex.liu/schema/beans" 
		xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
		targetNamespace="http://www.spex.liu/schema/beans">
    
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace"/>
    
    <xsd:element name="property">
	    <xsd:complexType>
	    	<xsd:choice minOccurs="0" maxOccurs="1">
	    		<xsd:element ref="bean"/>
				<xsd:element ref="list"/>
				<xsd:element ref="set"/>
				<xsd:element ref="map"/>
	    	</xsd:choice>
	    	
	    	<xsd:attribute name="name" type="xsd:string" use="required" />
	    	<xsd:attribute name="value" type="xsd:string" />
	    	<xsd:attribute name="ref" type="xsd:string" />
	    </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="constructor-arg">
    	<xsd:complexType>
	    	<xsd:choice minOccurs="0" maxOccurs="1">
	    		<xsd:element ref="bean"/>
				<xsd:element ref="list"/>
				<xsd:element ref="set"/>
				<xsd:element ref="map"/>
	    	</xsd:choice>
	    	
	    	<xsd:attribute name="index" type="xsd:string" />
	    	<xsd:attribute name="name" type="xsd:string" />
	    	<xsd:attribute name="type" type="xsd:string" />
	    	<xsd:attribute name="ref" type="xsd:string" />
	    	<xsd:attribute name="value" type="xsd:string" />
	    </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="beans">
    	<xsd:complexType>
    		<xsd:choice minOccurs="0" maxOccurs="unbounded">
    			<xsd:element ref="bean" />
    		</xsd:choice>
    	</xsd:complexType>
    </xsd:element>
    
    <xsd:element name="bean">
    	<xsd:complexType>
    	
    		<!-- children elements -->
    		<xsd:choice minOccurs="0" maxOccurs="unbounded">
    			<xsd:element ref="property" />
    			<xsd:element ref="constructor-arg" />
    		</xsd:choice>
    		
    		<!-- attributes -->
    		<xsd:attribute name="id" type="xsd:string" />
    		<xsd:attribute name="class" type="xsd:string" />
    		<xsd:attribute name="depends-on" type="xsd:string" />
    		<xsd:attribute name="init-method" type="xsd:string" />
    		<xsd:attribute name="factory-bean" type="xsd:string" />
    		<xsd:attribute name="factory-method" type="xsd:string" />
    		<xsd:attribute name="autowire" default="byName">
    			<xsd:simpleType>
    				<xsd:restriction base="xsd:NMTOKEN">
    					<xsd:enumeration value="no" />
    					<xsd:enumeration value="byName" />
    					<xsd:enumeration value="byType" />
    				</xsd:restriction>
    			</xsd:simpleType>
    		</xsd:attribute>
    		<xsd:attribute name="primary" type="xsd:boolean" />
    	</xsd:complexType>
    </xsd:element>
    
    <xsd:element name="list">
    	<xsd:annotation>
    		<xsd:documentation><![CDATA[
    	no attribute
    		]]></xsd:documentation>
    	</xsd:annotation>
    	
    	<xsd:complexType>
    		<xsd:complexContent>
    			<xsd:extension base="collectionType">
    				<xsd:group ref="collectionElements"/>
    			</xsd:extension>
    		</xsd:complexContent>
    	</xsd:complexType>
    </xsd:element>
    
    <xsd:element name="set">
    	<xsd:annotation>
    		<xsd:documentation><![CDATA[
    	no attribute
    		]]></xsd:documentation>
    	</xsd:annotation>
    	
    	<xsd:complexType>
    		<xsd:complexContent>
    			<xsd:extension base="collectionType">
    				<xsd:group ref="collectionElements"/>
    			</xsd:extension>
    		</xsd:complexContent>
    	</xsd:complexType>
    </xsd:element>
    
    <xsd:element name="map">
    	<xsd:annotation>
    		<xsd:documentation><![CDATA[
    	no attribute
    		]]></xsd:documentation>
    	</xsd:annotation>
    	
    	<xsd:complexType>
    		<xsd:choice>
    			<xsd:element name="entry" type="entryType" />
    		</xsd:choice>
    	</xsd:complexType>
    </xsd:element>
    
    <xsd:element name="value">
    	<xsd:annotation>
    		<xsd:documentation><![CDATA[
    	no attribute
    		]]></xsd:documentation>
    	</xsd:annotation>
    </xsd:element>
    
    <xsd:group name="collectionElements">
    	<xsd:sequence>
    		<xsd:choice minOccurs="0" maxOccurs="unbounded">
    			<xsd:element ref="bean"/>
				<xsd:element ref="list"/>
				<xsd:element ref="set"/>
				<xsd:element ref="map"/>
				<xsd:element ref="value"/>
    		</xsd:choice>
    	</xsd:sequence>
    </xsd:group>
    
	<xsd:complexType name="entryType">
   		<xsd:complexContent>
   			<xsd:extension base="collectionType">
   				<xsd:group ref="collectionElements"/>
				<xsd:attribute name="key-type" type="xsd:string" use="required"/>
   			</xsd:extension>
   		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:complexType name="collectionType">
 		<xsd:attribute name="value-type" type="xsd:string"/>
	</xsd:complexType>
</xsd:schema>

=== Smile-Liu/spex/spex-test/src/config/spex-all.xml
<beans xmlns="http://www.spex.liu/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.spex.liu/schema/beans 
						http://www.spex.liu/schema/beans/spex-beans.xsd">

	<bean id="tom" class="org.spex.test.all.TestPropertyBean" primary="true">
		<property name="name" value="tom" />
		<property name="parentNames">
			<list>
				<value>t</value>
				<value>m</value>
			</list>
		</property>
	</bean>
	
	<bean id="lucy" class="org.spex.test.all.TestPropertyBean">
		<property name="name" value="lucy" />
		<property name="parentNames">
			<list>
				<value>l</value>
				<value>c</value>
			</list>
		</property>
	</bean>
	
	<bean id="jekky" class="org.spex.test.all.TestPropertyBean">
		<property name="name" value="jekky" />
		<property name="parentNames">
			<list>
				<value>j</value>
				<value>k</value>
			</list>
		</property>
	</bean>
	
	<bean id="family" class="org.spex.test.all.TestBean" autowire="byType">
		<property name="name" value="mouse-amily"/>
	</bean>
	
</beans>
